name: WakaTime Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  wakatime:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/wakatime.svg
          token: NOT_NEEDED
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_limit: 5
